# Explore here

In [453]:
import pandas as pd
import numpy as np

In [454]:
df= pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv')
df.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [455]:
df.columns

Index(['package_name', 'review', 'polarity'], dtype='object')

In [456]:
df.drop('package_name', axis= 1, inplace= True)
df.head()

review  polarity
0   privacy at least put some option appear offli...         0
1   messenger issues ever since the last update, ...         0
2   profile any time my wife or anybody has more ...         0
3   the new features suck for those of us who don...         0
4   forced reload on uploading pic on replying co...         0

In [457]:
print(df['review'])

0       privacy at least put some option appear offli...
1       messenger issues ever since the last update, ...
2       profile any time my wife or anybody has more ...
3       the new features suck for those of us who don...
4       forced reload on uploading pic on replying co...
                             ...                        
886     loved it i loooooooooooooovvved it because it...
887     all time legendary game the birthday party le...
888     ads are way to heavy listen to the bad review...
889     fun works perfectly well. ads aren't as annoy...
890     they're everywhere i see angry birds everywhe...
Name: review, Length: 891, dtype: object


In [458]:
#0 negativo, 1 positivo
# df['review'] = df['review'].str.strip().str.lower().replace('[^\w\s]', '', regex= True)
import re

df['review'] = df['review'].str.strip().str.lower().apply(lambda x: re.sub(r'[^a-zA-Z0-9\s]', '', x))
df.head()

review  polarity
0  privacy at least put some option appear offlin...         0
1  messenger issues ever since the last update in...         0
2  profile any time my wife or anybody has more t...         0
3  the new features suck for those of us who dont...         0
4  forced reload on uploading pic on replying com...         0

In [459]:
from sklearn.model_selection import train_test_split

X = df['review']
y = df['polarity']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 11)

X_train.head()

333    good app for call and texting overall everythi...
662    i do not have word to appreciate this  so just...
382    the fail boat has arrived the 60 version is to...
331    just did the latest update on viber and yet ag...
149    not able to play automatic closing since last ...
Name: review, dtype: object

In [460]:
X_train.to_csv("../data/processed/X_train.csv", index = False)
X_test.to_csv("../data/processed/X_test.csv", index = False)
y_train.to_csv("../data/processed/y_train.csv", index = False)
y_test.to_csv("../data/processed/y_test.csv", index = False)

In [461]:
from sklearn.feature_extraction.text import CountVectorizer

vec_model = CountVectorizer(stop_words = 'english')
X_train = vec_model.fit_transform(X_train).toarray()
X_test = vec_model.transform(X_test).toarray()

X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [462]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [463]:
y_pred = model.predict(X_train)
y_pred

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,

In [464]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_pred)

0.9620786516853933

In [465]:
y_pred_test = model.predict(X_test)
y_pred_test

array([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0])

In [466]:
accuracy_score(y_test, y_pred_test)

0.8324022346368715

In [467]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

models = [(BernoulliNB(), 'Bernoulli'), (MultinomialNB(), 'Multinomial'), (GaussianNB(), 'Gaussian')]

min_difference = float('inf')  # Establecer en infinito positivo
best_model = None
best_model_name = ''

for model, name in models:
    model.fit(X_train, y_train)
    
    y_pred_train = model.predict(X_train)
    train_acc = accuracy_score(y_train, y_pred_train)
    print(f'{name} Train accuracy: {train_acc}')

    y_pred_test = model.predict(X_test)
    test_acc = accuracy_score(y_test, y_pred_test)
    print(f'{name} Test accuracy: {test_acc}')

    diff = abs(train_acc - test_acc)

    if diff < min_difference:
        min_difference = diff
        best_model = model
        best_model_name = name

print(f'The best model is: {best_model_name} with the difference ({min_difference:.2f}) between train/test accuracy')

Bernoulli Train accuracy: 0.9367977528089888
Bernoulli Test accuracy: 0.7877094972067039
Multinomial Train accuracy: 0.9620786516853933
Multinomial Test accuracy: 0.8324022346368715
Gaussian Train accuracy: 0.9831460674157303
Gaussian Test accuracy: 0.7486033519553073
The best model is: Multinomial with the difference (0.13) between train/test accuracy


In [468]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import RandomizedSearchCV

# Modelo Multinomial Naive Bayes
model = MultinomialNB()

# Búsqueda de hiperparámetros para el modelo MultinomialNB
hyperparams = {
    'alpha': np.linspace(0.01, 10.0, 200),  # Modifica según tus necesidades
    'fit_prior': [True, False],
    'class_prior': [None,  np.arange(0, 30.0, 0.5)]
}

# Inicializar la búsqueda aleatoria
random_search = RandomizedSearchCV(model, hyperparams, n_iter= 50, scoring= 'accuracy', cv= 5, random_state= 11)
random_search.fit(X_train, y_train)

/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning: 
130 fits failed out of a total of 250.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
130 fits failed with the following error:
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/sklearn/naive_bayes.py", line 775, in fit

RandomizedSearchCV(cv=5, estimator=MultinomialNB(), n_iter=50,
                   param_distributions={'alpha': array([ 0.01      ,  0.06020101,  0.11040201,  0.16060302,  0.21080402,
        0.26100503,  0.31120603,  0.36140704,  0.41160804,  0.46180905,
        0.51201005,  0.56221106,  0.61241206,  0.66261307,  0.71281407,
        0.76301508,  0.81321608,  0.86341709,  0.91361809,  0.9638191 ,
        1.0140201 ,  1.06422111,  1.11442211,  1.1646231...
        9.79919598,  9.84939698,  9.89959799,  9.94979899, 10.        ]),
                                        'class_prior': [None,
                                                        array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5])],
                                        'fit_prior': [True, False]},
                   random_state=11, scoring='accuracy')

In [469]:
# Obtener los mejores hiperparámetros
best_params = random_search.best_params_
print(f'Best hyperparameters: {best_params}')

Best hyperparameters: {'fit_prior': False, 'class_prior': None, 'alpha': 4.277085427135678}


In [470]:
model = MultinomialNB(alpha = 4.277085427135678, fit_prior = False, class_prior= None)
model.fit(X_train, y_train)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test, y_pred)

0.8435754189944135

In [471]:
y_pred_tr = model.predict(X_train)
accuracy_score(y_train, y_pred_tr)

0.9241573033707865

In [472]:
from pickle import dump

dump(model, open('../models/nb_alpha_4-27708542_fit_prior_False_class_prior-None.pk', "wb"))